version: 1

sources:
  - name: raw
    database: railway 
    schema: ecommerce_data
    tables:
      - name: olist_orders_dataset
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_customer_dataset
      - name: olist_sellers_dataset
      - name: olist_products_dataset
      - name: product_category_name_translation
      - name: olist_closed_deals_dataset
      - name: olist_marketing_qualified_leads_dataset
      - name: olist_geolocation_dataset
      - name: olist_order_reviews_dataset