version: 1

sources:
  - name: raw
    database: ecommerce_data 
    schema: public
    tables:
      - name: olist_orders_dataset
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_customer_dataset
      - name: olist_sellers_dataset
